apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 10.244.0.132/32
    cni.projectcalico.org/podIPs: 10.244.0.132/32
  creationTimestamp: "2020-07-24T10:04:29Z"
  generateName: prometheus-deployment-7bcc89959f-
  labels:
    app: prometheus-server
    pod-template-hash: 7bcc89959f
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
        f:labels:
          .: {}
          f:app: {}
          f:pod-template-hash: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"7acef62d-5254-4e4b-a371-94444f20d6ba"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:containers:
          k:{"name":"prometheus"}:
            .: {}
            f:args: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:ports:
              .: {}
              k:{"containerPort":9090,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:protocol: {}
            f:resources: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/etc/prometheus/"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/prometheus/"}:
                .: {}
                f:mountPath: {}
                f:name: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:terminationGracePeriodSeconds: {}
        f:volumes:
          .: {}
          k:{"name":"prometheus-config-volume"}:
            .: {}
            f:configMap:
              .: {}
              f:defaultMode: {}
              f:name: {}
            f:name: {}
          k:{"name":"prometheus-storage-volume"}:
            .: {}
            f:emptyDir: {}
            f:name: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-07-24T10:04:29Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:cni.projectcalico.org/podIP: {}
          f:cni.projectcalico.org/podIPs: {}
    manager: calico
    operation: Update
    time: "2020-07-24T10:04:30Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.244.0.132"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    time: "2020-07-24T10:04:33Z"
  name: prometheus-deployment-7bcc89959f-v7z97
  namespace: monitoring
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: prometheus-deployment-7bcc89959f
    uid: 7acef62d-5254-4e4b-a371-94444f20d6ba
  resourceVersion: "393767"
  selfLink: /api/v1/namespaces/monitoring/pods/prometheus-deployment-7bcc89959f-v7z97
  uid: 8767e2ec-8bc1-4fac-8231-dfc6f7204576
spec:
  containers:
  - args:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus/
    image: prom/prometheus:v2.2.1
    imagePullPolicy: Always
    name: prometheus
    ports:
    - containerPort: 9090
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/prometheus/
      name: prometheus-config-volume
    - mountPath: /prometheus/
      name: prometheus-storage-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-hc62z
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: kube-node01
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      name: prometheus-server-conf
    name: prometheus-config-volume
  - emptyDir: {}
    name: prometheus-storage-volume
  - name: default-token-hc62z
    secret:
      defaultMode: 420
      secretName: default-token-hc62z
status:
  conditions:
  - lastProbeTime: 5s
    lastTransitionTime: "2020-07-24T10:04:29Z"
    status: "True"
    type: Initialized
  - lastProbeTime: 5s
    lastTransitionTime: "2020-07-24T10:04:33Z"
    status: "True"
    type: Ready
  - lastProbeTime: 5s
    lastTransitionTime: "2020-07-24T10:04:33Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: 5s
    lastTransitionTime: "2020-07-24T10:04:29Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://d0b783ef262b8c667c8d8e7882410c48c158e86b57af0152026fd3411568083e
    image: prom/prometheus:v2.2.1
    imageID: docker-pullable://prom/prometheus@sha256:129e16b08818a47259d972767fd834d84fb70ca11b423cc9976c9bce9b40c58f
    lastState: {}
    name: prometheus
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-07-24T10:04:33Z"
  hostIP: 192.168.1.12
  phase: Running
  podIP: 10.244.0.132
  podIPs:
  - ip: 10.244.0.132
  qosClass: BestEffort
  startTime: "2020-07-24T10:04:29Z"
