apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 10.244.238.4/32
    cni.projectcalico.org/podIPs: 10.244.238.4/32
  creationTimestamp: "2020-07-24T08:27:12Z"
  generateName: prometheus-deployment-54686956bd-
  labels:
    app: prometheus-server
    pod-template-hash: 54686956bd
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:cni.projectcalico.org/podIP: {}
          f:cni.projectcalico.org/podIPs: {}
    manager: calico
    operation: Update
    time: "2020-07-24T08:27:12Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
        f:labels:
          .: {}
          f:app: {}
          f:pod-template-hash: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"26052afb-3f38-4c99-aa82-00d3e37eefe1"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:containers:
          k:{"name":"prometheus"}:
            .: {}
            f:args: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:ports:
              .: {}
              k:{"containerPort":9090,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:protocol: {}
            f:resources: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/etc/prometheus/"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/prometheus/"}:
                .: {}
                f:mountPath: {}
                f:name: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:terminationGracePeriodSeconds: {}
        f:volumes:
          .: {}
          k:{"name":"prometheus-config-volume"}:
            .: {}
            f:configMap:
              .: {}
              f:defaultMode: {}
              f:name: {}
            f:name: {}
          k:{"name":"prometheus-storage-volume"}:
            .: {}
            f:emptyDir: {}
            f:name: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-07-24T08:27:12Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.244.238.4"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    time: "2020-07-24T08:27:28Z"
  name: prometheus-deployment-54686956bd-mg4ff
  namespace: monitoring
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: prometheus-deployment-54686956bd
    uid: 26052afb-3f38-4c99-aa82-00d3e37eefe1
  resourceVersion: "380140"
  selfLink: /api/v1/namespaces/monitoring/pods/prometheus-deployment-54686956bd-mg4ff
  uid: 2a877ffc-7907-478e-85ed-7e8e6c51ba0b
spec:
  containers:
  - args:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus/
    image: prom/prometheus
    imagePullPolicy: Always
    name: prometheus
    ports:
    - containerPort: 9090
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/prometheus/
      name: prometheus-config-volume
    - mountPath: /prometheus/
      name: prometheus-storage-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-hc62z
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: kube-node02
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      name: prometheus-server-conf
    name: prometheus-config-volume
  - emptyDir: {}
    name: prometheus-storage-volume
  - name: default-token-hc62z
    secret:
      defaultMode: 420
      secretName: default-token-hc62z
status:
  conditions:
  - lastProbeTime: 5s
    lastTransitionTime: "2020-07-24T08:27:12Z"
    status: "True"
    type: Initialized
  - lastProbeTime: 5s
    lastTransitionTime: "2020-07-24T08:27:28Z"
    status: "True"
    type: Ready
  - lastProbeTime: 5s
    lastTransitionTime: "2020-07-24T08:27:28Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: 5s
    lastTransitionTime: "2020-07-24T08:27:12Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://3e1d7a768589d5540fd53fbb401cd4700f8ea59aaa67b0341bbee8a3f58f1413
    image: prom/prometheus:latest
    imageID: docker-pullable://prom/prometheus@sha256:d4ba4dd1a9ebb90916d0bfed3c204adcb118ed24546bf8dd2e6b30fc0fd2009e
    lastState: {}
    name: prometheus
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-07-24T08:27:27Z"
  hostIP: 192.168.1.13
  phase: Running
  podIP: 10.244.238.4
  podIPs:
  - ip: 10.244.238.4
  qosClass: BestEffort
  startTime: "2020-07-24T08:27:12Z"
